id: P4781E4BC
initial_creation_type: input
source_metadata:
  title: Tupten Chöpel
  language: bo
  description: 'Texts by the great Khenpo Tupten Chöpel (thub bstan chos ''phel, 1886–1956)
    also known as Tubga Yishyin Norbu (thub dga'' yid bzhin nor bu) of Changma hermitage
    in Dzachukha:'
  volume:
    3198dda04183456190b085e9fb57243c:
      title: Aspiration Prayer
      parent: Aspiration Prayers
created_at: '2022-03-01T02:00:07.178960'
last_modified_at: '2022-03-01T02:00:07.178962'
